# Generated by Django 3.2 on 2021-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imsuser',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('ST', 'Staff'), ('CU', 'Customer')], default='AD', max_length=255),
        ),
    ]
