# Generated by Django 3.2 on 2021-04-16 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imsuser',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='imsuser',
            name='Landline_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number should be in correct format'. Up to 15 digits allowed.   ", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='imsuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number should be in correct format'. Up to 15 digits allowed.   ", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='imsuser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imsuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
