# Generated by Django 3.2 on 2021-05-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_users', '0002_alter_imsuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='imsuser',
            name='pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imsuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
