# Generated by Django 3.2 on 2021-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipt',
            name='quantity',
            field=models.TextField(default='1,1'),
            preserve_default=False,
        ),
    ]
