# Generated by Django 3.2 on 2021-05-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerOrders',
            new_name='recipt',
        ),
        migrations.RemoveField(
            model_name='productvarientitems',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productvarientitems',
            name='product_varient_id',
        ),
        migrations.DeleteModel(
            name='productVarient',
        ),
        migrations.DeleteModel(
            name='productVarientItems',
        ),
    ]
