# Generated by Django 3.2 on 2021-07-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrecords',
            name='recipt',
        ),
        migrations.AddField(
            model_name='customerrecords',
            name='recipt',
            field=models.ManyToManyField(to='product.Recipt'),
        ),
    ]
