# Generated by Django 3.2 on 2021-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customerrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecords',
            name='purchased_date',
            field=models.DateField(null=True),
        ),
    ]
