# Generated by Django 3.2 on 2021-07-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210730_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrecords',
            name='purchased_date',
        ),
    ]
