# Generated by Django 3.2 on 2021-06-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210531_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='added_by_staff',
        ),
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/categories/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='url_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/subcategories/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='url_slug',
            field=models.SlugField(unique=True),
        ),
    ]
