# Generated by Django 3.2 on 2021-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_recipt_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='original_stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
