# Generated by Django 3.2 on 2021-06-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210606_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='media_content',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='productMedia',
        ),
    ]
