# Generated by Django 3.2 on 2021-07-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_customerrecords_purchased_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecords',
            name='purchased_product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.recipt'),
        ),
    ]
