# Generated by Django 3.2 on 2021-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_customerrecords_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipt',
            name='unique_token',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
