# Generated by Django 3.2 on 2021-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_recipt_unique_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipt',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
