# Generated by Django 3.2 on 2021-07-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_customerrecords_purchased_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrecords',
            old_name='user_id',
            new_name='imsuser',
        ),
        migrations.RenameField(
            model_name='customerrecords',
            old_name='purchased_product_id',
            new_name='recipt',
        ),
    ]
