# Generated by Django 3.2 on 2021-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210729_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipt',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='recipt',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='recipt',
            name='product_status',
        ),
        migrations.AddField(
            model_name='recipt',
            name='product',
            field=models.ManyToManyField(to='product.products'),
        ),
        migrations.AddField(
            model_name='recipt',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipt',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipt',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
